### ISSUE TITLE
feat: 서버 초기화 로직 변경

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#171]
# Feature

현재 프로그램에서 동적으로 수행하고 있는 초기화 작업을

DB 데이터 저장 + Meilisearch 동기화로 이분화 하고,

DB 데이터 저장은 golang-migrate를 통해 수행하고,
Meilisearch 동기화는 여러번 수행 가능 한 형태로 한다.

또한 운영서버는 API를 통해 동기화 하면 보안상 위험하므로, 별도의 프로그램을 통해 동기화를 진행한다.

# Todo List

- [x] devhelper 패키지 정리 및 동기화용 API 추가
- [x] 동기화 프로그램 모듈 추가
- [x] CI/CD 대응

# Additional Comment

운영 단계를 대비하기위한 작업
