### ISSUE TITLE
feat: 초기화 시 개발 관련 용어가 저장되도록 함

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#29]
# Feature

MVP를 위해 미리 작성된 개발 관련 용어가 초기화 시 저장 되도록 함

# Todo List

- [x] 기 작성 된 개발 용어를 Tsv 형태로 추출 후, 시스템에서 읽을 수 있게 함
- [x] 초기화 시 DB에 개발 관련 용어 저장
- [x] 초기화 시 Meilisearch에 개발 관련 용어 저장
