### ISSUE TITLE
feat: 기존 용어집 및 용어 API를 데모용 API로 변경하고 로직 분리

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#42]
# Feature

용어집 API와 용어 API를 데모용 API로 모으는 작업을 수행하고, 본 서비스 로직과 분리한다.

# Todo List

- [x] 용어집 API를 데모용 API로 변경
- [x] 용어 API를 데모용 API로 변경
- [x] 용어 및 용어집을 저장하는 Model을 데모용 용어 및 용어집 Model로 변경

# Additional Comment

1차 MVP로 만들 예정인 부분에 대해서는 데모용이기 때문에
실제로 만들 서비스와는 시간이 지날 수록 다른 요구사항을 수용해야 할 것이라고 예상 됨.
그에 따라 본 데모용으로 만들어진 API들을 데모용 API로 모으는 작업을 수행하고,
본 서비스를 위한 API와 로직을 분리한다.
