### ISSUE TITLE
feat: 데모 기획의 사양 축소 및 변경 대응

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#51]
# Feature

데모 기획의 화면 설계가 나옴으로서 기획이 정리 및 수정된 사항이 있으므로
이에 맞게 API 수정 작업을 수행

# Todo List

- [x] 데모에 필요없는 API 삭제
- [x] 데모에 맞게 모델링 구조 단순화
- [x] 검색 엔진 질의 시 정렬 기능 추가
