### ISSUE TITLE
feat: 계정 생성 및 추가 정보 수집 흐름 구현

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#53]
# Feature

계정 생성 및 추가 정보 수집 흐름 구현

# Todo List

- [x] 소셜 로그인 (구글)
- [x] 계정 생성
- [x] 회원의 현재 상태 확인
- [x] 약관 정보 조회
- [x] 회원 가입 (w/ 약관 동의 데이터)
- [x] 추가 정보 수집

# References

[계정 생성/수정/탈퇴 PRD](https://www.notion.so/PRD-c2f8208d68ef4ad1a144218ec0e86cfe)
