### ISSUE TITLE
feat: 약관 정보 삭제

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#62]
# Feature

약관은 변경되더라도 재동의를 받아야 하는 경우가 희박하고, DB를 이용한 버전 관리도 필요 없어 보이므로 API는 삭제하고, 약관 내용은 프론트에서 정적파일 서빙으로 대체

# Todo List

- [x] 약관 목록 API 삭제
- [x] 회원 가입 시 약관 동의 정보 형식 수정
- [x] 약관 관련 테이블 삭제 및 선택 약관 동의 여부 데이터 저장 공간 추가
