### ISSUE TITLE
feat: 온보딩 완료 API 수정

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#71]
# Feature

온보딩 API의 사용성 증가 및 예외 처리, 데이터 관리 방법 등을 수정

# Todo List

- [x] 온보딩 완료상태를 별도 관리
- [x] 온보딩 완료 API Path 변경 (/user/onboarding/complete -> /user/onboarding)
- [x] 비즈니스 규칙 위반에 대한 예외처리 및 문서화
