### ISSUE TITLE
feat: 용어집 관련 모델 생성 및 용어집 관리 API

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#81]
# Feature

용어집 관련 모델 생성 및 용어집 관리 API를 만든다.

# Todo List

- [x] 용어집 관련 모델
- [x] 용어집 조회 API
- [x] 용어집 생성 API
- [x] 용어집 수정 API
- [x] 용어집 삭제 API
