### ISSUE TITLE
feat: 용어 관리 API

### ISSUE THREAD

**Issue by seungyeop-lee** [makevook/vook-server#86]
# Feature

용어 관리 API를 만든다.

# Todo List

- [x] 용어 생성 API
- [x] 용어 조회 API
- [x] 용어 수정 API
- [x] 용어 삭제 API
